package langModel;

import static org.junit.Assert.*;

import java.util.ArrayList;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;


/**
 * This JUnit Test Class has been generated by right clicking on the MiscUtil class
 * and selecting "New > Junit Test Case". After that, you have to select the methods 
 * for which you would like to generate tests. 
 * In practice, you will duplicate manually the test methods to possibly create 
 * several tests for one method.
 * 
 * Your work is then to remove the fail parts and to implement each test.
 * One method is given as an example
 * 
 * To run them:
 * either right click on the class name or simply on the method name and
 * select "Run As Junit Test".
 * 
 * @author N. Hernandez and S. Quiniou (2015)
 *
 */
public class NgramUtilTest {
	String sentence = "<s> cette phrase est de taille 9 . </s>";
	String ngram = "où commence l' historique de cet n-gramme";
	
	
	/**
	 * Test method for {@link langModel.NgramUtil#getSequenceSize(java.lang.String)}.
	 */
	@Test
	public void testGetSequenceSize() {
	
		System.out.println(NgramUtil.getSequenceSize(sentence));
		// on the left the expected value and on the right the actual one 
		// (i.e. the one returned by your method)
		assertEquals(9, NgramUtil.getSequenceSize(sentence));
	}

	
	/**
	 * Test method for {@link langModel.NgramUtil#generateNgrams(java.lang.String, int, int)}.
	 */
	@Test
	public void testGenerateNgrams() {
		System.out.println(NgramUtil.generateNgrams(sentence, 1, 2));
		ArrayList<String> listTest = new ArrayList<String>();
		listTest.add("<s>");
		listTest.add("cette");
		listTest.add("phrase");
		listTest.add("est");
		listTest.add("de");
		listTest.add("taille");
		listTest.add("9");
		listTest.add(".");
		listTest.add("</s>");
		listTest.add("<s> cette");
		listTest.add("cette phrase");
		listTest.add("phrase est");
		listTest.add("est de");
		listTest.add("de taille");
		listTest.add("taille 9");
		listTest.add("9 .");
		listTest.add(". </s>");
		
		assertEquals(listTest,NgramUtil.generateNgrams(sentence, 1, 2) );
	}

	
	/**
	 * Test method for {@link langModel.NgramUtil#getHistory(java.lang.String, int)}.
	 */
	@Test
	public void testGetHistory() {
		assertEquals("historique de cet", NgramUtil.getHistory(ngram, 4));
		assertEquals("de cet", NgramUtil.getHistory(ngram, 3));
		assertEquals("cet", NgramUtil.getHistory(ngram, 2));
		assertEquals("", NgramUtil.getHistory(ngram, 1));
	}

	
	/**
	 * Test method for {@link langModel.NgramUtil#decomposeIntoNgrams(java.lang.String, int)}.
	 */
	@Test
	public void testDecomposeIntoNgrams() {
		System.out.println(NgramUtil.decomposeIntoNgrams(sentence, 2));
		ArrayList<String> listTest = new ArrayList<String>();
		listTest.add("<s>");
		listTest.add("<s> cette");
		listTest.add("cette phrase");
		listTest.add("phrase est");
		listTest.add("est de");
		listTest.add("de taille");
		listTest.add("taille 9");
		listTest.add("9 .");
		listTest.add(". </s>");
		
		assertEquals(listTest,NgramUtil.decomposeIntoNgrams(sentence, 2) );	
	}
	
	
	/**
	 * The following code displays a separator 
	 * between each method output
	 * 
	 * (manually added)
	 **/
	@Rule
	public TestName name = new TestName();

	@Before
	public void printSeparator()
	{
		System.out.println("\n=== " + name.getMethodName() + " =====================");
	}

}
